### ISSUE TITLE
Error during multi-regression training / ValueError: arrays must all be same length

### ISSUE THREAD

**Issue by jim-schwoebel** [jim-schwoebel/allie#34]
```
(featurize.py:17787): Gdk-CRITICAL **: 13:59:10.995: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
audio-features-44c7f080-e56a-11ea-9f66-380025122270: 100%|███████| 5010/5010 [00:10<00:00, 456.12it/s]
numerical
-------------
Traceback (most recent call last):
  File "featurize_csv_regression.py", line 417, in <module>
    df, filename=csv_featurize(options.input, options.output, settings, options.target)
  File "featurize_csv_regression.py", line 383, in csv_featurize
    df = pd.DataFrame(newdict)
  File "/home/jim/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/home/jim/.local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 257, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/jim/.local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 77, in arrays_to_mgr
    index = extract_index(arrays)
  File "/home/jim/.local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 368, in extract_index
    raise ValueError("arrays must all be same length")
ValueError: arrays must all be same length
```

**Comment by jim-schwoebel** [comment]
This seems to be a problem only with multiple featurizations. May need to look at the loop in the csv_features_regression.py script

**Comment by jim-schwoebel** [comment]
Fixed with https://github.com/jim-schwoebel/allie/commit/fa69b40ea018b2459f4765ad38216b23ce28e732
